### ISSUE TITLE
dbt 0.20.0 support

### ISSUE THREAD

**Issue by jamesrayoub** [fivetran/dbt_quickbooks_source#14]
update to support dbt 0.20.0

**Comment by fivetran-joemarkiewicz** [comment]
Hey @jamesrayoub thanks for opening this Issue as well as Issue #15. I am currently making these updates across our packages this week. I will prioritize QuickBooks to be one of the early packages. I will post back here with any updates!

**Comment by fivetran-joemarkiewicz** [comment]
@jamesrayoub quickbooks_source `v0.3.0` is now live on the dbt hub! 

Let me know if you have any further questions or requests when upgrading.
