### ISSUE TITLE
Cast deposit_to_account_id as integer

### ISSUE THREAD

**Issue by jamesrayoub** [fivetran/dbt_quickbooks_source#8]
In the Invoice staging model, `deposit_to_account_id` is currently represented as a string, but since we cast `account_id` in the Accounts model as an integer, this FK should also be cast as an int

**Comment by fivetran-joemarkiewicz** [comment]
Thanks for catching this @jamesrayoub! We are planning an enhancement to the dbt_quickbooks package to include a monthly P&L model. We will incorporate this fix in those updates.

**Comment by fivetran-joemarkiewicz** [comment]
This issue has been addressed within PR #9 and is now live within Release v0.2.0. 

Keep an eye out on the dbt hub for when it is officially released!
